const Data = [
    {
        "company": "Recyclan Global",
        "name": "Credit Financing",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-83f8a565-9fa6-4d5c-9052-04d2df736b9b",
        "id": "INV-83f8a565-9fa6-4d5c-9052-04d2df736b9b",
        "cycle": "7 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "fixed income",
        "amt": 2120,
        "like": false,
        "completed": true,
        "expected_returns": "14% in 7 Months",
        "percent": 14,
        "returns": "14% in 7 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 62,
        "closing_date": "15 Jul 2021",
        "maturity_date": "15 Jul 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Keshy Farms",
        "name": "Cashew Nut Investment",
        "location": "Kano Nigeria",
        "url": "/dashboard/investify/explore/view_investment/INV-ba66853c-4b33-440e-aa13-1fe59e9e8b91",
        "id": "INV-ba66853c-4b33-440e-aa13-1fe59e9e8b91",
        "cycle": "12 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 2530,
        "like": false,
        "completed": true,
        "expected_returns": "23% in 12 Months",
        "percent": 23,
        "returns": "23% in 12 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 49,
        "closing_date": "24 Dec 2021",
        "maturity_date": "24 Dec 2021",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Dave Farms",
        "name": "Cassava Farm Investment",
        "location": "Lagos Nigeria",
        "url": "/dashboard/investify/explore/view_investment/INV-def5e80d-ca9e-4f10-a518-7a8bfd07f129",
        "id": "INV-def5e80d-ca9e-4f10-a518-7a8bfd07f129",
        "cycle": "1 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 3570,
        "like": false,
        "completed": true,
        "expected_returns": "28% in 1 Months",
        "percent": 28,
        "returns": "28% in 1 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 84,
        "closing_date": "29 Jan 2021",
        "maturity_date": "29 Jan 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Tele Transports",
        "name": "Transport Investments",
        "location": "Abuja Nigeria and France",
        "url": "/dashboard/investify/explore/view_investment/INV-68f39527-5326-47fd-bcc6-e48565deb1db",
        "id": "INV-68f39527-5326-47fd-bcc6-e48565deb1db",
        "cycle": "7 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "transport",
        "amt": 4790,
        "like": false,
        "completed": true,
        "expected_returns": "1% in 7 Months",
        "percent": 1,
        "returns": "1% in 7 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 97,
        "closing_date": "2 Jul 2021",
        "maturity_date": "2 Jul 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Speedy Logistics",
        "name": "Logistics Investment",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-96554a27-af0a-486b-b97a-5c22f1dcc485",
        "id": "INV-96554a27-af0a-486b-b97a-5c22f1dcc485",
        "cycle": "8 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "transport",
        "amt": 3180,
        "like": false,
        "completed": true,
        "expected_returns": "6% in 8 Months",
        "percent": 6,
        "returns": "6% in 8 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 24,
        "closing_date": "7 Aug 2021",
        "maturity_date": "7 Aug 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Bekky Farms",
        "name": "Potato Farm Investment",
        "location": "Abuja Nigeria",
        "url": "/dashboard/investify/explore/view_investment/INV-61b77b34-5f51-4da2-a8a6-7e90ac27cccb",
        "id": "INV-61b77b34-5f51-4da2-a8a6-7e90ac27cccb",
        "cycle": "7 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 2160,
        "like": false,
        "completed": true,
        "expected_returns": "23% in 7 Months",
        "percent": 23,
        "returns": "23% in 7 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 57,
        "closing_date": "24 Jul 2021",
        "maturity_date": "24 Jul 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Legit Realtors",
        "name": "Legit Real Estate",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-6cb2c664-2910-4f1c-9da4-8c72a4b3595f",
        "id": "INV-6cb2c664-2910-4f1c-9da4-8c72a4b3595f",
        "cycle": "8 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "real estate",
        "amt": 4390,
        "like": false,
        "completed": true,
        "expected_returns": "7% in 8 Months",
        "percent": 7,
        "returns": "7% in 8 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 47,
        "closing_date": "8 Aug 2021",
        "maturity_date": "8 May 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Miki Transports/Logistics",
        "name": "Logistics Investment",
        "location": "Abuja Nigeria and France",
        "url": "/dashboard/investify/explore/view_investment/INV-3f234485-4ce7-4c6a-93ed-56d272408dbe",
        "id": "INV-3f234485-4ce7-4c6a-93ed-56d272408dbe",
        "cycle": "12 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "transport",
        "amt": 2310,
        "like": false,
        "completed": true,
        "expected_returns": "6% in 12 Months",
        "percent": 6,
        "returns": "6% in 12 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 92,
        "closing_date": "7 Dec 2021",
        "maturity_date": "7 Jan 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Adele Livestocks",
        "name": "Cattle Hereder Investment",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-6bc888c3-a4ee-4270-82f8-fed13fe84a27",
        "id": "INV-6bc888c3-a4ee-4270-82f8-fed13fe84a27",
        "cycle": "7 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "transport",
        "amt": 1280,
        "like": false,
        "completed": true,
        "expected_returns": "4% in 7 Months",
        "percent": 4,
        "returns": "4% in 7 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 64,
        "closing_date": "5 Jul 2021",
        "maturity_date": "5 Jul 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Lake Rice",
        "name": "Rice Investment",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-cde60e35-e8a4-472d-bf45-5fd8937d3486",
        "id": "INV-cde60e35-e8a4-472d-bf45-5fd8937d3486",
        "cycle": "12 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 4600,
        "like": false,
        "completed": true,
        "expected_returns": "28% in 12 Months",
        "percent": 28,
        "returns": "28% in 12 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 2,
        "closing_date": "29 Dec 2020",
        "maturity_date": "29 Apr 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Nestle PLC",
        "name": "Maize Investment",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-15be776d-4526-42d4-ab55-58a84044efef",
        "id": "INV-15be776d-4526-42d4-ab55-58a84044efef",
        "cycle": "10 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 4900,
        "like": false,
        "completed": true,
        "expected_returns": "21% in 10 Months",
        "percent": 21,
        "returns": "21% in 10 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 35,
        "closing_date": "22 Oct 2020",
        "maturity_date": "22 Oct 2021",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Reinvest Global",
        "name": "Credit Financing",
        "location": "Abuja Nigeria and France",
        "url": "/dashboard/investify/explore/view_investment/INV-f6ce559d-3773-43a3-a490-931201834a39",
        "id": "INV-f6ce559d-3773-43a3-a490-931201834a39",
        "cycle": "6 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "fixed income",
        "amt": 5600,
        "like": false,
        "completed": true,
        "expected_returns": "6% in 6 Months",
        "percent": 6,
        "returns": "6% in 6 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 85,
        "closing_date": "7 Jun 2021",
        "maturity_date": "7 Jun 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Gavi Farms",
        "name": "Tomato Investment",
        "location": "Abuja Nigeria",
        "url": "/dashboard/investify/explore/view_investment/INV-1fdfc05a-7003-4102-8059-f02124e3fb14",
        "id": "INV-1fdfc05a-7003-4102-8059-f02124e3fb14",
        "cycle": "8 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 3050,
        "like": false,
        "completed": true,
        "expected_returns": "25 in 8 Months",
        "percent": 25,
        "returns": "25 in 8 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 91,
        "closing_date": "26 Aug 2020",
        "maturity_date": "26 Aug 2021",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Hope Gardens",
        "name": "Flower Investment",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-425378c5-c6ff-4fd5-a5d9-b46731f6e079",
        "id": "INV-425378c5-c6ff-4fd5-a5d9-b46731f6e079",
        "cycle": "12 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 7700,
        "like": false,
        "completed": true,
        "expected_returns": "7% in 12 Months",
        "percent": 7,
        "returns": "7% in 12 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 94,
        "closing_date": "8 Dec 2020",
        "maturity_date": "8 Dec 2021",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Lekki Gardens",
        "name": "Real Estate",
        "location": "Lagos Nigeria and UK",
        "url": "/dashboard/investify/explore/view_investment/INV-31b43756-d5e8-45ef-b5e2-b0c0f1fed8f0",
        "id": "INV-31b43756-d5e8-45ef-b5e2-b0c0f1fed8f0",
        "cycle": "11 Months",
        "type": "investment",
        "category": "real estate",
        "Category": "transport",
        "amt": 3190,
        "like": false,
        "completed": true,
        "expected_returns": "24% in 11 Months",
        "percent": 24,
        "returns": "24% in 11 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 48,
        "closing_date": "25 Nov 2020",
        "maturity_date": "25 Nov 2021",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    },
    {
        "company": "Dave Fish Farm",
        "name": "Fish Investment",
        "location": "Kogi Nigeria",
        "url": "/dashboard/investify/explore/view_investment/INV-95ca9398-b382-4d30-b3b6-4c3507db8406",
        "id": "INV-95ca9398-b382-4d30-b3b6-4c3507db8406",
        "cycle": "6 Months",
        "type": "investment",
        "category": "ongoing",
        "Category": "agriculture",
        "amt": 4900,
        "like": false,
        "completed": true,
        "expected_returns": "23% in 6 Months",
        "percent": 23,
        "returns": "23% in 6 Months",
        "investment_type": "ROI",
        "nxtparam": "Investors",
        "nxtvalue": 72,
        "closing_date": "24 Jun 2021",
        "maturity_date": "24 Jun 2022",
        "payout_type": "Bank Transfer",
        "unit_type": "10",
        "insurance_partner": "Leadway Assurance"
    }
]

export default Data;