const date = new Date();

const genDays = (day) => {
    const diff = new Date(day).getTime() - date.getTime();
    if(diff <= 0) return "Completed";
    else return Math.floor(diff/(3600*1000*24));
}
const rates = (start, end) => {
    const st = new Date(start).getTime();
    const diff = (date.getTime()-st) / (new Date(end).getTime()-st);
    if(diff >= 1) return "100";
    else return Math.max(0, Math.floor(diff*100));
}
const iscompleted = (day) => {
    return new Date(day).getTime() <= date.getTime();
}

const Data = [
    {
        "name": "Team 100k by 2022",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-013745fc-e4da-4ddc-89ae-55e7a7f5576b",
        "url": "/dashboard/savings/target/explore/view_target/TAR-013745fc-e4da-4ddc-89ae-55e7a7f5576b/*",
        "Category": "vacation",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 100000,
        "amttype": "Group Balance",
        "target": 100000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 11,
        "start_date": "29 Jun 2022",
        "end_date": "29 Nov 2022",
        "completed": iscompleted("29 Nov 2022"),
        "members": 5,
        "rate": rates("29 Jun 2022","29 Nov 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("29 Nov 2022")
    },
    {
        "name": "2022 Savings",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-ade208cb-7e64-4707-8775-61cc8a54c6f9",
        "url": "/dashboard/savings/target/explore/view_target/TAR-ade208cb-7e64-4707-8775-61cc8a54c6f9/*",
        "Category": "rent",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 98000,
        "amttype": "Group Balance",
        "target": 98000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 83,
        "start_date": "29 Feb 2022",
        "end_date": "30 Sep 2022",
        "completed": iscompleted("30 Sep 2022"),
        "members": 5,
        "rate": rates("29 Feb 2022", "30 Sep 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("30 Sep 2022")
    },
    {
        "name": "Save Big With Nora",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-d54c5b10-b9c4-4f38-9667-c32771d1d570",
        "url": "/dashboard/savings/target/explore/view_target/TAR-d54c5b10-b9c4-4f38-9667-c32771d1d570/*",
        "Category": "fees",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 132000,
        "amttype": "Group Balance",
        "target": 132000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 96,
        "start_date": "20 Mar 2022",
        "end_date": "25 Dec 2022",
        "completed": iscompleted("25 Dec 2022"),
        "members": 5,
        "rate": rates("20 Mar 2022", "25 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("25 Dec 2022")
    },
    {
        "name": "MTC Savings Group",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-7cfa67b6-ba20-44ad-b407-834eda16797e",
        "url": "/dashboard/savings/target/explore/view_target/TAR-7cfa67b6-ba20-44ad-b407-834eda16797e/*",
        "Category": "Car/Vehicle",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 258000,
        "amttype": "Group Balance",
        "target": 258000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 84,
        "start_date": "29 Jan 2022",
        "end_date": "30 Nov 2022",
        "completed": iscompleted("30 Nov 2022"),
        "members": 5,
        "rate": rates("29 Jan 2022", "30 Nov 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("30 Nov 2022")
    },
    {
        "name": "Soft Christmas",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-795c0fbb-2755-4d09-a68b-aa23fffc1eec",
        "url": "/dashboard/savings/target/explore/view_target/TAR-795c0fbb-2755-4d09-a68b-aa23fffc1eec/*",
        "Category": "vacation",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 497000,
        "amttype": "Group Balance",
        "target": 497000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 10,
        "start_date": "29 Dec 2021",
        "end_date": "25 Dec 2023",
        "completed": iscompleted("25 Dec 2023"),
        "members": 5,
        "rate": rates("29 Dec 2021", "25 Dec 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("25 Dec 2023")
    },
    {
        "name": "New whip",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-ecd9d355-6f48-4261-a478-39c3bff62bb7",
        "url": "/dashboard/savings/target/explore/view_target/TAR-ecd9d355-6f48-4261-a478-39c3bff62bb7/*",
        "Category": "Car/Vehicle",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 246000,
        "amttype": "Group Balance",
        "target": 246000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 26,
        "start_date": "29 Jan 2022",
        "end_date": "26 Apr 2023",
        "completed": iscompleted("26 Apr 2023"),
        "members": 5,
        "rate": rates("29 Jan 2022", "26 Apr 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("26 Apr 2023")
    },
    {
        "name": "New House",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-3852d135-f451-4ff7-a3f0-9eecbc5c5470",
        "url": "/dashboard/savings/target/explore/view_target/TAR-3852d135-f451-4ff7-a3f0-9eecbc5c5470/*",
        "Category": "rent",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 178000,
        "amttype": "Group Balance",
        "target": 178000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 70,
        "start_date": "29 May 2022",
        "end_date": "29 Jul 2023",
        "completed": iscompleted("29 Jul 2023"),
        "members": 5,
        "rate": rates("29 May 2022", "29 Jul 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("29 Jul 2023")
    },
    {
        "name": "New Phone",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-9ddec2fe-1d85-43e1-af8b-1acfc5c90ccf",
        "url": "/dashboard/savings/target/explore/view_target/TAR-9ddec2fe-1d85-43e1-af8b-1acfc5c90ccf/*",
        "Category": "gadgets",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 298000,
        "amttype": "Group Balance",
        "target": 298000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 34,
        "start_date": "01 Jan 2022",
        "end_date": "31 Dec 2022",
        "completed": iscompleted("31 Dec 2022"),
        "members": 5,
        "rate": rates("01 Jan 2022", "31 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("31 Dec 2022")
    },
    {
        "name": "School Fees",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-c8daac23-6d62-4f00-b133-26f05959c9d3",
        "url": "/dashboard/savings/target/explore/view_target/TAR-c8daac23-6d62-4f00-b133-26f05959c9d3/*",
        "Category": "education",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 295000,
        "amttype": "Group Balance",
        "target": 295000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 9,
        "start_date": "19 Mar 2022",
        "end_date": "15 Mar 2023",
        "completed": iscompleted("15 Mar 2023"),
        "members": 5,
        "rate": rates("19 Mar 2022", "15 Mar 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("15 Mar 2023")
    },
    {
        "name": "New Business",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-b2f0bba4-dd06-437f-92d9-a851235dc495",
        "url": "/dashboard/savings/target/explore/view_target/TAR-b2f0bba4-dd06-437f-92d9-a851235dc495/*",
        "Category": "business",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 234000,
        "amttype": "Group Balance",
        "target": 234000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 9,
        "start_date": "09 Jul 2021",
        "end_date": "09 Jul 2022",
        "completed": iscompleted("09 Jul 2022"),
        "members": 5,
        "rate": rates("09 Jul 2021", "09 Jul 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("09 Jul 2022")
    },
    {
        "name": "Travelling",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-d6d2c440-c09a-4c9c-ae17-19e175381654",
        "url": "/dashboard/savings/target/explore/view_target/TAR-d6d2c440-c09a-4c9c-ae17-19e175381654/*",
        "Category": "vacation",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 343000,
        "amttype": "Group Balance",
        "target": 343000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 55,
        "start_date": "29 Dec 2021",
        "end_date": "29 Mar 2023",
        "completed": iscompleted("29 Mar 2023"),
        "members": 5,
        "rate": rates("29 Dec 2021", "29 Mar 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("29 Mar 2023")
    },
    {
        "name": "Cruise",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-fa11f208-37c5-4ba3-99e4-708a214ece51",
        "url": "/dashboard/savings/target/explore/view_target/TAR-fa11f208-37c5-4ba3-99e4-708a214ece51/*",
        "Category": "vacation",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 97000,
        "amttype": "Group Balance",
        "target": 97000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 73,
        "start_date": "29 Apr 2022",
        "end_date": "29 Dec 2022",
        "completed": iscompleted("29 Dec 2022"),
        "members": 5,
        "rate": rates("29 Apr 2022", "29 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("29 Dec 2022")
    },
    {
        "name": "Birthday Party",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-ea99becf-bb8b-4975-82e1-b1c291567a90",
        "url": "/dashboard/savings/target/explore/view_target/TAR-ea99becf-bb8b-4975-82e1-b1c291567a90/*",
        "Category": "events",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 190000,
        "amttype": "Group Balance",
        "target": 190000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 93,
        "start_date": "29 Feb 2022",
        "end_date": "31 Dec 2022",
        "completed": iscompleted("31 Dec 2022"),
        "members": 5,
        "rate": rates("29 Feb 2022", "31 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("31 Dec 2022")
    },
    {
        "name": "Get Together Party",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-63c2d431-3fd3-49cd-a238-24c90be5b596",
        "url": "/dashboard/savings/target/explore/view_target/TAR-63c2d431-3fd3-49cd-a238-24c90be5b596/*",
        "Category": "events",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 454000,
        "amttype": "Group Balance",
        "target": 454000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 92,
        "start_date": "29 Oct 2021",
        "end_date": "29 Dec 2022",
        "completed": iscompleted("29 Dec 2022"),
        "members": 5,
        "rate": rates("29 Oct 2021", "29 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("29 Dec 2022")
    },
    {
        "name": "Big Savings",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-6bc3c232-e760-4a25-82ec-cb816c5d01a2",
        "url": "/dashboard/savings/target/explore/view_target/TAR-6bc3c232-e760-4a25-82ec-cb816c5d01a2/*",
        "Category": "business",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 322000,
        "amttype": "Group Balance",
        "target": 322000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 58,
        "start_date": "29 Jan 2021",
        "end_date": "31 Jul 2022",
        "completed": iscompleted("31 Jul 2022"),
        "members": 5,
        "rate": rates("29 Jan 2021", "31 Jul 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("31 Jul 2022")
    },
    {
        "name": "Go Fund Me",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-75dfab01-f532-43e8-b103-2ccf3d6e1ad8",
        "url": "/dashboard/savings/target/explore/view_target/TAR-75dfab01-f532-43e8-b103-2ccf3d6e1ad8/*",
        "Category": "fees",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 295000,
        "amttype": "Group Balance",
        "target": 295000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 7,
        "start_date": "29 Jul 2022",
        "end_date": "27 Jul 2023",
        "completed": iscompleted("27 Jul 2023"),
        "members": 5,
        "rate": rates("29 Jul 2022", "27 Jul 2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("27 Jul 2023")
    },
    {
        "name": "New Schoes",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-63221fda-7afb-42a0-a491-5ceb561f2858",
        "url": "/dashboard/savings/target/explore/view_target/TAR-63221fda-7afb-42a0-a491-5ceb561f2858/*",
        "Category": "fees",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 67000,
        "amttype": "Group Balance",
        "target": 67000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 59,
        "start_date": "29 Apr 2022",
        "end_date": "31 Dec 2022",
        "completed": iscompleted("31 Dec 2022"),
        "members": 5,
        "rate": rates("29 Apr 2022", "31 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("31 Dec 2022")
    },
    {
        "name": "Vacation",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-cb87d223-b773-49f5-ba2f-53dedaa4c2c0",
        "url": "/dashboard/savings/target/explore/view_target/TAR-cb87d223-b773-49f5-ba2f-53dedaa4c2c0/*",
        "Category": "vacation",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 73000,
        "amttype": "Group Balance",
        "target": 73000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 7,
        "start_date": "29 Jul 2022",
        "end_date": "01 Dec 2022",
        "completed": iscompleted("01 Dec 2022"),
        "members": 5,
        "rate": rates("29 Jul 2022", "01 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("01 Dec 2022")
    },
    {
        "name": "New Startup",
        "type": "vacation",
        "category": "ongoing",
        "id": "TAR-93af2b45-06f0-42c3-bccb-439c6b11f0fd",
        "url": "/dashboard/savings/target/explore/view_target/TAR-93af2b45-06f0-42c3-bccb-439c6b11f0fd/*",
        "Category": "business",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 141000,
        "amttype": "Group Balance",
        "target": 141000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 57,
        "start_date": "20 Mar 2022",
        "end_date": "31 Dec 2022",
        "completed": iscompleted("31 Dec 2022"),
        "members": 5,
        "rate": rates("20 Mar 2022", "31 Dec 2022"),
        "lock": false,
        "break": false,
        "days_left": genDays("31 Dec 2022")
    },
    {
        "name": "Wedding",
        "type": "savings",
        "category": "ongoing",
        "id": "TAR-0c24ec02-d809-4a74-9866-ee0b2e7bec08",
        "url": "/dashboard/savings/target/explore/view_target/TAR-0c24ec02-d809-4a74-9866-ee0b2e7bec08/*",
        "Category": "event",
        "friends": [
            "Bayo",
            "Bose",
            "Ade",
            "Bruno",
            "Roddy"
        ],
        "savings_preference": "Daily",
        "image_url": null,
        "time": "1 p.m",
        "frequency": "50",
        "amt": 263000,
        "amttype": "Group Balance",
        "target": 263000,
        "interest": "10%",
        "nxtparam": "Days Left",
        "nxtvalue": 8,
        "start_date": "09 Jul 2022",
        "end_date": "09 Jul  2023",
        "completed": iscompleted("09 Jul  2023"),
        "members": 5,
        "rate": rates("09 Jul 2022", "09 Jul  2023"),
        "lock": false,
        "break": false,
        "days_left": genDays("09 Jul  2023")
    }
]

export default Data;